language: python

python: 
  - "3.5"

install:
  - pip install jupyter
  - pip install numpy
  - pip install matplotlib
  - pip install pandas
  - pip install scipy

before_script:
  - jupyter nbconvert --to script 'BankMining.ipynb'

script:
  - python BankMining.py
