language: python

python: 
  - "3.5"

install:
  - pip install jupyter
  - pip install numpy
  - pip install matplotlib
  - pip install pandas
  - pip install scipy

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - jupyter nbconvert --to script 'BankMining.ipynb'

script:
  - python BankMining.py
